sonar.projectKey=GabrielBoelter_prova03-e2e-Gabriel-Custodio-Boelter
sonar.organization=gabrielboelter
sonar.projectName=Prova 03
sonar.projectVersion=1.0
sonar.sources=./src
sonar.sourceEncoding=UTF-8
